version: '3'

services:
    
  db:
    image: postgres:10.1-alpine
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
        
  backend:
    build: .
    # restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
    # command: bash -c "cd masterytest && 
    #                   python manage.py makemigrations --no-input &&
    #                   python manage.py migrate &&
    #                   python manage.py test product.tests.test_views"

    command: bash -c "cd masterytest && 
                      python manage.py makemigrations --no-input &&
                      python manage.py migrate &&
                      python manage.py collectstatic --no-input &&
                      python manage.py loaddata test_data &&
                      python manage.py runserver 0.0.0.0:8000"

    # command: bash -c "cd masterytest && 
    #                   python manage.py makemigrations --no-input &&
    #                   python manage.py migrate &&
    #                   python manage.py runserver 0.0.0.0:8000"
    
    volumes:
      - .:/code
      - ./media:/code/media
    ports:
      - "8000:8000"
         
# volumes:
  # postgres_data:
