version: '3'

services:
    
  db:
    image: postgres:10.1-alpine
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
        
  backend:
    build: .
    # restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
    command: bash -c "cd masterytest && 
                      python manage.py makemigrations --no-input &&
                      python manage.py migrate &&
                      python manage.py test"
    ports:
      - "8000"
         
# volumes:
  # postgres_data:
